### ISSUE TITLE
Output formatting

### ISSUE THREAD

**Issue by deniapps** [SwimComm/hytek-parser#1]
This is great!
But the output of the parser appears to be a lengthy unformatted text. Would it be more appropriate to return it as an Array or JSON data?

**Comment by egelja** [comment]
I'm not sure what you mean. Which specific parser are you referencing?

**Comment by deniapps** [comment]
Hi! Thank you for getting back to me. I am new to Python, here is what I did:
```
import hytek_parser
results = hytek_parser.parse_hy3("./files/eex2022.hy3")
```
If I print the results, I get something like this:
```
ParsedHytekFile(file_description='Results From MM to TM', software=Software(name='Hy-Tek, Ltd', version='MM5 8.0Ea'), date_created=datetime.datetime(2023, 9, 1, 9, 52), licensee='..., meet=Meet(name='...', facility='...', start_date=datetime.date(2022, 12, 16), end_date=datetime.date(2022, 12, 18), altitude=0, country='USA', masters=False, type_=<MeetType.INVITATIONAL: '01'>, course=<Course.SCY: 'Y'>, teams={....}......
```
Is it "Object to String" or something?
I thought it would return me structured data, like this:
```
{
fileDescription: "...",
software: "...",
teams: [],
swimmers: []
event:[]
...
}
```
Then I figured out something like this:
```
results = hytek_parser.parse_hy3("./files/eex-holiday-2022.hy3")

# via dir(), I am able to find out the attributes of the swimmer object:
# 'age', 'date_of_birth', 'first_name', 'gender', 'last_name', 'meet_id', 'middle_initial', 'nick_name', 'team_code',

events = results.meet.events
meetSwimmers = []
for key, event in events.items():
    entries = event.entries
    for entry in entries:
        for swimmer in entry.swimmers:
            meetSwimmers.append({
                "age": swimmer.age,
                "firstName": swimmer.first_name
            })
print(json.dumps(meetSwimmers))
```
So now, I am able to get the JSON data of swimmers data. Is it the right way to do it? Or there is an easy way to convert results to JSON string?

**Comment by egelja** [comment]
> Hi! Thank you for getting back to me. I am new to Python, here is what I did:
> 
> ```
> import hytek_parser
> results = hytek_parser.parse_hy3("./files/eex2022.hy3")
> ```
> 
> If I print the results, I get something like this:
> 
> ```
> ParsedHytekFile(file_description='Results From MM to TM', software=Software(name='Hy-Tek, Ltd', version='MM5 8.0Ea'), date_created=datetime.datetime(2023, 9, 1, 9, 52), licensee='..., meet=Meet(name='...', facility='...', start_date=datetime.date(2022, 12, 16), end_date=datetime.date(2022, 12, 18), altitude=0, country='USA', masters=False, type_=<MeetType.INVITATIONAL: '01'>, course=<Course.SCY: 'Y'>, teams={....}......
> ```
> 
> Is it "Object to String" or something?

Yes, this is the string representation of the parsed data.

> I thought it would return me structured data, like this:
> 
> ```
> {
> fileDescription: "...",
> software: "...",
> teams: [],
> swimmers: []
> event:[]
> ...
> }
> ```

It does! Are you familiar with classes? I know the documentation isn't the best, but if you look, `parse_hy3` returns a [`ParsedHytekFile`](https://github.com/SwimComm/hytek-parser/blob/b6098c3076bcf7a402a16a4f3659f2ebd4f11ddd/hytek_parser/hy3/schemas.py#L386). You can then use `ParsedHytekFile.meet` to get the meet, `Meet.events` to get the events, etc. See the [`schemas.py` file](https://github.com/SwimComm/hytek-parser/blob/master/hytek_parser/hy3/schemas.py) for all the data classes.

> So now, I am able to get the JSON data of swimmers data. Is it the right way to do it? Or there is an easy way to convert results to JSON string?

All the data classes are `attrs` classes, so you can just use [`attrs.asdict`](https://www.attrs.org/en/stable/examples.html#converting-to-collections-types) and then dump to JSON:

```py
import attrs
import hytek_parser
import json

results = hytek_parser.parse_hy3("./files/eex2022.hy3")
json.dumps(attrs.asdict(results))
```

**Comment by deniapps** [comment]
Hi! Thank you so much for getting back to me!

I understand the Class/Object concept, but I am unfamiliar with Python Syntax. 
I tried the snippet you provided, and got the following error:
```
  File ".../Python/hytek-parser/hytek_parser/run.py", line 6, in <module>
    json.dumps(attrs.asdict(results))
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```
I attached the hy3 file (please rename it to .hy3, for GitHub does not allow me to attach the hy3 file). Could you please check it out and let me know if you are able to parse the file?

I really appreciate your help!

Adam
[eex-holiday-2022.txt](https://github.com/SwimComm/hytek-parser/files/10451741/eex-holiday-2022.txt)

**Comment by deniapps** [comment]
ChatGPT told me:
> This error message is raised when you are trying to use the attrs library's attrs.asdict() function on a class that is not decorated with the attrs decorator.
>
> The attrs.asdict() function is intended to be used on attrs-decorated classes, and will raise this error if it is used on a class that is not decorated with attrs.
>
> To fix this error, you need to decorate the class with the attrs decorator, like this: 

I see you use `@define ` in the class, should I change it to `@attrs.s`, for example:
```python
# from attrs import Factory, define, field
import attrs

# @define(init=False)
@attrs.s
class Swimmer:
    """Represents a swimmer in a meet."""

    # Biological info? If you have a better name tell me.
    gender: Gender
    date_of_birth: date
    age: int
```

**Comment by egelja** [comment]
No ChatGPT is wrong. Attrs has been updated to use `@define`. Notice how `define` is imported from `attrs`.

The error isn't even in attrs.

>TypeError: Object of type datetime is not JSON serializable

Here's a printout of the dictionary, JSON serialization is a tad bit more complex.

```py
import attrs
import hytek_parser
import pprint

results = hytek_parser.parse_hy3("./files/eex2022.hy3")
d = attrs.asdict(results)

pprint.pprint(d)
```

JSON:
```py
import attrs
import hytek_parser
import orjson

results = hytek_parser.parse_hy3("./files/eex2022.hy3")
d = attrs.asdict(results)

print(
    orjson.dumps(
        d,
        option=orjson.OPT_NON_STR_KEYS | orjson.OPT_NAIVE_UTC | orjson.OPT_INDENT_2 | orjson.OPT_SORT_KEYS,
        default=str
     ).decode()
)
```

Remove `| orjson.OPT_INDENT_2 | orjson.OPT_SORT_KEYS` for non pretty-printing

**Comment by deniapps** [comment]
Hi! @MrAwesomeRocks Sorry for the late response. I did test this as you suggested, and it works perfectly. I really appreciate your help. I have some other issues, but I will reach out when possible.
