### ISSUE TITLE
AttributeError: 'ParsedHytekFile' object has no attribute 'meet'

### ISSUE THREAD

**Issue by supchin** [SwimComm/hytek-parser#3]
[meet.zip](https://github.com/SwimComm/hytek-parser/files/15287198/meet.zip)
Hi, the hy3 file is attached.  This is the code I am running. 

```
import attrs
import hytek_parser
import pprint

input_file = r'.\h3file\meet.hy3'
results = hytek_parser.parse_hy3(input_file)

d = attrs.asdict(results)

pprint.pprint(d)
```

When I run this, I get the following error:

`Traceback (most recent call last):
  File "c:\Users\xyz\OneDrive\Project\hytekparser.py", line 9, in <module>
    d = attrs.asdict(results)
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\OneDrive\Project\.venv\Lib\site-packages\attr\_next_gen.py", line 198, in asdict
    return _asdict(
           ^^^^^^^^
  File "C:\Users\xyz\OneDrive\Project\.venv\Lib\site-packages\attr\_funcs.py", line 57, in asdict
    v = getattr(inst, a.name)
        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ParsedHytekFile' object has no attribute 'meet'`

I am assuming it's because the file doesn't have an attribute 'meet', how do I get around this?

**Comment by egelja** [comment]
I'll make a new release after #5 merges

**Comment by egelja** [comment]
Version 1.1.1 has been published with the fix for this issue.
