### ISSUE TITLE
ValueError: time data does not match format '%d%m%Y %I:%M %p'

### ISSUE THREAD

**Issue by hansenmc** [SwimComm/hytek-parser#4]
When reading a hy3 file with Entries, an Exception was encountered when parsing the dateTime of the event on the first line:

`A102Meet Entries             Hy-Tek, Ltd    Win-TM 8.0Ga  06272024 12:00 PMOakton Swim Team`  

Results in:

>   File "c:\code\hytek_parser\hy3_parser.py", line 64, in parse_hy3
>     parsed_file = line_parser(line, parsed_file, opts)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\code\hytek_parser\hy3\line_parsers\a_file_parsers.py", line 20, in a1_parser
>     file.date_created = datetime.strptime(raw_date, "%d%m%Y %I:%M %p")
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\_strptime.py", line 554, in _strptime_datetime
>     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\_strptime.py", line 333, in _strptime
>     raise ValueError("time data %r does not match format %r" %
> ValueError: time data '06272024 12:00 PM' does not match format '%d%m%Y %I:%M %p'

https://github.com/SwimComm/hytek-parser/blob/b6098c3076bcf7a402a16a4f3659f2ebd4f11ddd/hytek_parser/hy3/line_parsers/a_file_parsers.py#L20

It seems the date pattern `%d%m%y` should instead be `%m%d%y`.

**Comment by egelja** [comment]
Oh wow I can't believe I missed that. I guess the files I tested on always were from the 12th or before, and I must have just guessed wrong.

Mind opening a PR to fix that?
