### ISSUE TITLE
ValueError: invalid literal for int() with base 10:"" when Meet Altitude missing

### ISSUE THREAD

**Issue by hansenmc** [SwimComm/hytek-parser#6]
Encountered a ValueError for `meet.altitude` in the b_meet_parsers.py

> Traceback (most recent call last):
>   File "c:\code\hytek-parser\hytek_parser\hy3_parser.py", line 62, in parse_hy3
>     parsed_file = line_parser(line, parsed_file, opts)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\code\hytek-parser\hytek_parser\hy3\line_parsers\b_meet_parsers.py", line 19, in b1_parser
>     meet.altitude = int(extract(line, 117, 5))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: invalid literal for int() with base 10: ''

https://github.com/SwimComm/hytek-parser/blob/master/hytek_parser/hy3/line_parsers/b_meet_parsers.py#L19

Need to either skip or assign a default value when Altitude value is not specified in the file.

**Comment by egelja** [comment]
Yep that should probably be changed to use `safe_cast`

**Comment by hansenmc** [comment]
Wondering how you want to handle default values for missing numbers? Make it `0`, `-1`, or `None`?

Not sure if it needs to worry about trimming whitespace chars or not, and whether to set default value:

    meet.altitude = int(extract(line, 117, 5).strip() or 0)

or would you want to skip setting if a number isn't specified (might pose issues if something expects that property to have a value)?

        if altitude := extract(line, 117, 5).strip().isdigit():
            meet.altitude = int(altitude)

I think am going to encounter other issues with things such as Swimmer team_id.

**Comment by egelja** [comment]
I'd say set it to `None` if its invalid

You'll also have to change this line

https://github.com/SwimComm/hytek-parser/blob/813517727f30cadccfedabacd9521fb618da4fa7/hytek_parser/hy3/schemas.py#L251

**Comment by hansenmc** [comment]
`safe_cast(int, "", None)` and `safe_cast(int, None, None)` both return `0`

So, can either use `safe_cast()` and have it default to `0` or would need a different function/logic to set it to `None`. Also, if it does default to `None` - then change the types from `int` to `int|None`?

**Comment by egelja** [comment]
Let's make it default to None. Feel free to add another function to that utils.py file if needed.

> Also, if it does default to None - then change the types from int to int|None?

Yep, exactly.

**Comment by egelja** [comment]
#8
