### ISSUE TITLE
AttributeError: 'Swimmer' object has no attribute 'team_id' in same_swimmer_entry_as()

### ISSUE THREAD

**Issue by hansenmc** [SwimComm/hytek-parser#7]
Encountered error:
```
  File "c:\code\hytek-parser\hytek_parser\hy3\schemas.py", line 164, in same_swimmer_entry_as
    self.swimmers == other.swimmers
  File "<attrs generated eq hytek_parser.hy3.schemas.Swimmer>", line 13, in __eq__
AttributeError: 'Swimmer' object has no attribute 'team_id'. Did you mean: 'team_code'?
```

https://github.com/SwimComm/hytek-parser/blob/master/hytek_parser/hy3/schemas.py#L164

Swimmer does not have `team_id` and that is causing issues with `same_swimmer_entry_as()`

**Comment by hansenmc** [comment]
`team_id` is conditionally set in d_swimmer_parsers.py:

https://github.com/SwimComm/hytek-parser/blob/master/hytek_parser/hy3/line_parsers/d_swimmer_parsers.py#L25 

So may need to set with a default value, such as `-1`:

    swimmer.team_id = int(extract(line, 84, 5) or -1)

 or change how Swimmer comparison works.

**Comment by egelja** [comment]
Yea, that should probably default to `None` too. 

https://github.com/SwimComm/hytek-parser/blob/813517727f30cadccfedabacd9521fb618da4fa7/hytek_parser/hy3/schemas.py#L35

**Comment by egelja** [comment]
#8

**Comment by hansenmc** [comment]
I created a fresh venv and install hytek_parser. It shows version 1.1.1 is installed, but still getting this error. Looking at what was published, it doesn't seem to have this fix applied - though it does have version updated in hytek_parser/__init__.py

Could there have been an issue bundling files for the release? Is there a chance we could get this re-published, or maybe new version with https://github.com/SwimComm/hytek-parser/pull/15 ?

**Comment by egelja** [comment]
I'll make a new release sometime next week... sorry, things have been hectic recently.
