### ISSUE TITLE
Event number with alphaNumeric values always parsed as 0

### ISSUE THREAD

**Issue by hansenmc** [SwimComm/hytek-parser#9]
Event Number can have more than just `int` values. It is common to have event number with a suffix "1A", "1B", or "1X" (exhibition).

HyTek Team Manager and Meet Manager allow for alphanumeric values for the Event #. 
In Team Manager it displays the event with Event# column showing the number and then the alpha characters in the unlabeled column next to it. 
In Meet Manager it displays the value in the "Evt#" column.
Swimtopia also supports these "Event Number" values with alphaNumeric values.

When parsing the Event, it extracts the 4 characters from the 39th position and uses safe_cast() to produce an `int` value.
https://github.com/SwimComm/hytek-parser/blob/master/hytek_parser/hy3/line_parsers/e_event_parsers.py#L37

If there are any non-numeric values, it produces the integer value `0` for those event numbers.

[Event.event_number](https://github.com/SwimComm/hytek-parser/blob/master/hytek_parser/hy3/schemas.py#L81) either needs to be `str`, adjusted to `tuple(int, str)`, or an EventNumber class that can represent both the number and the qualifier.

**Comment by egelja** [comment]
Huh... I've never seen alphanumeric event numbers. Guess that was an oversight on my part.

Probably would be best to just change `Event.event_number` to be a string.
